//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SR_ECOM_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livraison
    {
        public long Liv_Id { get; set; }
        public Nullable<int> Mode_Liv_Id { get; set; }
        public Nullable<long> Cmd_Id { get; set; }
        public Nullable<System.DateTime> Liv_Date { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Mode_Livraison Mode_Livraison { get; set; }
    }
}
