//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SR_ECOM_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateur()
        {
            this.Commande = new HashSet<Commande>();
        }
    
        public int Utili_Id { get; set; }
        public string Utili_Login { get; set; }
        public string Utili_Mdp { get; set; }
        public string Utili_Nom { get; set; }
        public string Utili_Prenom { get; set; }
        public string Utili_Profil { get; set; }
        public string Utili_Num_Tel { get; set; }
        public string Utili_Sexe { get; set; }
        public string Utili_Adresse { get; set; }
        public string Utili_Code_Poste { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commande { get; set; }
    }
}
